-- local qmk = require 'qmk'
-- qmk.setup({
--     name = 'LAYOUT_60_ansi_split_bs_rshift',             -- identify your layout name
--     comment_preview = {
--         keymap_overrides = {
--             HERE_BE_A_LONG_KEY = 'Magic',             -- replace any long key codes
--         },
--     },
--     layout = {               -- create a visual representation of your final layout
--         'x x x x x x x x x x x x x x x',             -- including keys that span multple rows (with alignment left, center or right)
--         'x^ x x x x ^xxx x x x x x x x',             -- including keys that span multple rows (with alignment left, center or right)
--         'x x x ^xxxxxxxxxxxxxx x x x x',             -- including keys that span multple rows (with alignment left, center or right)
--     },
-- })
